// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2YHfzmW88oeZ8U2wiV4MRv1W8Iav25g',
    appId: '1:226265609466:web:d2baf638e0fe934b090543',
    messagingSenderId: '226265609466',
    projectId: 'what-for-dinner-d0f94',
    authDomain: 'what-for-dinner-d0f94.firebaseapp.com',
    storageBucket: 'what-for-dinner-d0f94.appspot.com',
    measurementId: 'G-QEFPKJQZ70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHaquphRUOLUVqNCWw_uKcd8WlH9Vb-UE',
    appId: '1:226265609466:android:83cb957b8a703a3a090543',
    messagingSenderId: '226265609466',
    projectId: 'what-for-dinner-d0f94',
    storageBucket: 'what-for-dinner-d0f94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQQaUcopwoiYjXa0Ui-u0BG0xE6frt7JE',
    appId: '1:226265609466:ios:40b018460f50e43f090543',
    messagingSenderId: '226265609466',
    projectId: 'what-for-dinner-d0f94',
    storageBucket: 'what-for-dinner-d0f94.appspot.com',
    iosClientId:
        '226265609466-afjhb58sputcm3fopvr9lguifl50ahj4.apps.googleusercontent.com',
    iosBundleId: 'pt.castanho.eatermeals',
  );
}
